---
## Use this to copy local ssh keys to a group of servers
# Before running bootstrap, you can use the 'local_action' version.
# Otherwise, this will work with the authorized_key module.
# 
# You may need to create an env variable to get this to work:
# export ANSIBLE_HOST_KEY_CHECKING=false
# 
# Tested on Linux OS systems.

- hosts: Linux:&ans-*
  remote_user: sysadmin
  gather_facts: False
  tasks:
    ## enable me to use ansible modules (you won't have to type password, but this requires pkgs installed
    - authorized_key:
        user: sysadmin
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    ##enable me to run ssh-copy-id on all servers
    #- set_fact: 
        #rem_host: "{{ ansible_host }}"
    #- local_action: command ssh-copy-id sysadmin@{{ rem_host }}  


