---

- name: Apply preflight
  hosts: Linux:&ans-*
  gather_facts: yes
  remote_user: sysadmin
  become: yes

  vars:
    cl_message: "Linux pre-flight ran on this host"

  roles:
    - lin_preflight
    - sophos
    - lin_tcp_wrappers
    - { role: lin_epel, when: ansible_os_family == 'RedHat' }
#    - maint_window

